@Library('MySharedLibrary') _

pipeline {
    agent {
        label 'jenkins-slave' // This is the agent used for the pipeline
    }

    parameters {
        string(defaultValue: '', description: '', name: 'BRANCH_NAME')
        choice(choices: ['DEBUG', 'RELEASE', 'TEST'], description: '', name: 'BUILD_TYPE')
    }

    stages {
        stage('process') {
            when {
                allOf {
                    expression { params.BRANCH_NAME == "master" }
                    expression { params.BUILD_TYPE == 'RELEASE' }
                }
            }
            steps {
                echo "Kicking off production build\n"
            }
        }
    }
}

