@Library('MySharedLibrary') _

pipeline {
    agent {
        label 'jenkins-slave' // This is the agent used for the pipeline
    }

    parameters {
        // String Parameter
        string(defaultValue: "maintainer", description: 'Enter user role:', name: 'userRole')

        // Choice Parameter
        choice(choices: ['DEBUG', 'RELEASE', 'TEST'], description: 'Choose build type', name: 'BUILD_TYPE')


	// Uncomment and configure these parameters as needed:
        // Boolean Parameter
        booleanParam(defaultValue: false, description: 'Should we run the tests?', name: 'RUN_TESTS')

        // Text Parameter
        text(defaultValue: '', description: 'Enter a detailed description of the build', name: 'BUILD_DESCRIPTION')




    }

    stages {
        stage('Print Parameter Values') {
            steps {
                script {
                    // Echo String Parameter
                    echo "User Role: ${params.userRole}"

                    // Echo Choice Parameter
                    echo "Build Type: ${params.BUILD_TYPE}"
		
		    // Boolean
		    echo "Run Tests: ${params.RUN_TESTS}"


   		    // Text Parameter
                    // Echo Text Parameter
                    echo "Build Description: ${params.BUILD_DESCRIPTION}"



                }
            }
        }
    }
}

