@Library('MySharedLibrary') _

pipeline {
    agent {
        label 'jenkins-slave' // This is the agent used for the pipeline
    }

    parameters {
        // String Parameter
        string(defaultValue: "maintainer", description: 'Enter user role:', name: 'userRole')

        // Choice Parameter
        choice(choices: ['DEBUG', 'RELEASE', 'TEST'], description: 'Choose build type', name: 'BUILD_TYPE')

    }

    stages {
        stage('Print Parameter Values') {
            steps {
                script {
                    // Echo String Parameter
                    echo "User Role: ${params.userRole}"

                    // Echo Choice Parameter
                    echo "Build Type: ${params.BUILD_TYPE}"

                }
            }
        }
    }
}

